### ISSUE TITLE
링크 잘 못 표기

### ISSUE THREAD

**Issue by AkiaCode** [meotitda/DICTIONARY#19]
### 자유롭게 작성해주세요.
---
![image](https://user-images.githubusercontent.com/71239005/98764691-ad98f200-241f-11eb-8ce2-fd881f5bbe86.png)

`다음 문서에서 확인` 이 부분을 클릭하면 문서가 안나오고 `https://github.com/meotitda` 로 가집니다

**Comment by MoonSupport** [comment]
문서가 아직 안만들어져서 문서를 만들고 링크를 수정하겠습니다 😇

**Comment by AkiaCode** [comment]
아하 알겠습니다 !

**Comment by MoonSupport** [comment]
해당 이슈로 이전합니다.

https://github.com/meotitda/DICTIONARY/issues/65
