### ISSUE TITLE
1. 오타 수정, 2. 문제에 정답이 써있음.

### ISSUE THREAD

**Issue by 372dev** [meotitda/DICTIONARY#23]
### 한글오타
---

일정 시간 동안의 입력을 모와서 <--

--> 모아서 혹은 모아와서

### 문제에 정답이 두번이나 표기됨
---
잔물결효과 <--

--> 그림파일에 답 나옴, 텍스트에 답 나옴 ripple effect

**Comment by MoonSupport** [comment]
이슈 보고 감사합니다 🤩

오타 수정했습니다 :)

그림파일에 답 나옴, 텍스트에 답 나옴 ripple effect 이슈 같은 경우에는 다음 업데이트와 관련 있어서, 추후에 적용하겠습니다 ㅎㅎ
