### ISSUE TITLE
Load 문제에 정답 기재되어있음.

### ISSUE THREAD

**Issue by seongkyu-lim** [meotitda/DICTIONARY#24]
---

문제를 풀어보았는데 load 단어에 문제 내용에 정답이 한글로 기재되어있습니다.

---

~~~ 

Load란 하중, 짐, <span style='color:#FFCC00; font-weight:bold;'>부하</span>라는 의미를 가진다.

컴퓨터의 작업 혹은 작업량을 뜻함.

로드가 많다는건 컴퓨터의 일이 많다는 것.

Load Balancing(로드 밸런싱)

부하분산 또는 로드 밸런싱은 컴퓨터 <span style="color:#FFBF00; font-weight:bold;">네트워크 기술의 일종으로 둘 혹은 셋이상의 중앙처리장치 혹은 저장장치와 같은 컴퓨터 자원들에게 작업을 나누는 것</span>을 의미한다. 이로써 가용성 및 응답시간을 최적화 시킬 수 있다.

~~~

-> 여기서 한글로 명시된 '로드'가 문제에서 그대로 나옵니다.

**Comment by mahns1201** [comment]
처리했습니다~!~!

**Comment by seongkyu-lim** [comment]
넵 확인하였습니다! 기능적인 부분을 명확히 이해하고 있지 않았는데 수정된 마크다운을 보니 영단어를 인식해서 ㅁㅁㅁ처리하나 보네요!

새로운 contributer분들을 위해 SyntaxDoc.md에 이에 대한 설명이 추가되면 좋을 것 같습니다!

**Comment by mahns1201** [comment]
> 넵 확인하였습니다! 기능적인 부분을 명확히 이해하고 있지 않았는데 수정된 마크다운을 보니 영단어를 인식해서 ㅁㅁㅁ처리하나 보네요!
> 
> 새로운 contributer분들을 위해 SyntaxDoc.md에 이에 대한 설명이 추가되면 좋을 것 같습니다!

좋은 조언 감사합니다. !!! 내용 추가하도록 하겠습니다 ㅎㅎㅎ
