### ISSUE TITLE
Lazy 단어를 추가해주세요!

### ISSUE THREAD

**Issue by MoonSupport** [meotitda/DICTIONARY#30]
### Lazy 단어 추가 기여를 기다리고 있습니다 :)

에디터 주소
https://meotitda.github.io/DICTIONARY-EDITOR/?word=Lazy

양식을 입력 후에 복사해서 바로 Propose 할 수 있습니다.
작성 파일은 반드시 *.md(마크다운) 파일로 생성하셔야 합니다.

단어를 추가하고 DICTIONARY의 Contributor가 되어보세요 🤩

> 만약 에디터를 사용할 수 없거나 Contribute에 대한 더 많은 정보를 얻고 싶으시다면  [해당 링크](https://github.com/meotitda/DICTIONARY/blob/master/docs/CONTRIBUTE.md)를 참고해주세요.

**Comment by roseline124** [comment]
이거 닫아도 될 듯?

**Comment by MoonSupport** [comment]
GOOD!
