### ISSUE TITLE
api 서버 리뉴얼

### ISSUE THREAD

**Issue by MoonSupport** [meotitda/DICTIONARY#63]

**Comment by mahns1201** [comment]
@MoonSupport 

현재 사용중인 DB와 운용은 어떻게 되고 있는지 궁금합니다 ! 그리고 DB도 리뉴얼 예정이 있으실까요?

**Comment by MoonSupport** [comment]
@mahns1201 인프라가 구축되지 전에 `master` 브랜치명 `main` 으로 바꿔두면 어떨까요?

어쨌든 git에서 `main`을 권장하고 있어서 작업할 때 좀 헷갈리네요.
인프라 리뉴얼 마치면 브랜치명 바꾸는데 공수가 들어갈꺼 같아서 미리 바꾸면 어떨까 싶습니다.

**Comment by mahns1201** [comment]
@MoonSupport
